version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "5569:5569"
    volumes:
      - .:/app/backend
  db-postgres-evento:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-evento"
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  database: